# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: M 3.3 Elektronik (ELK)
author: M. Meiners (HSB) 
copyright: ""
logo: images/hsb-logo.png
exclude_patterns: ["LICENSE.md", "README.md"]
only_build_toc_files: true
# Short description about the book
description: >-
  Bachelormodul.

# execute:
#  execute_notebooks: cache

# HTML-specific settings
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  home_page_in_navbar: true
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  navbar_number_sections: false
  baseurl: "https://mimeiners.github.io/elk/"
# google_analytics_id: UA-11111111 # add your Google Analytics Tracking Code
  comments:
    hypothesis: false
    utterances:
      repo: "mimeiners/elk"
    dokieli: true
  extra_footer : |
      <div>
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
          All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>
      </div>
      
# Launch button settings
launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"
  thebe: true
  
repository:
  url: https://github.com/mimeiners/elk
  path_to_book: ""
  branch: master


# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine: "xelatex"
  latex_documents:
    targetname: elk.tex

sphinx:
  config:
    html_show_copyright: false
    html_extra_path: ['files']
    bibtex_reference_style: author_year
    myst_enable_extensions: 
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - substitution

    myst_substitutions:
      INSTRUCTOR: "Prof. Dr.-Ing. Mirco Meiners (he/his/him)"
      PRONOUNCE: ""
      OFFICE: "E 508"
      PHONE: "N/A"
      COURSE_CODE: "M 3.3"
      SECTION: ""
      CREDITS: "6"
      TITLE: "Elektronik (ELK)"
      PREREQS: "GEL1, GEL2"
      COREQS: ""
      TERM: "2022/23 Winter"
      ROOM: "E 507"
      MEETING_TIMES: "Dienstags von 8:00-13:00 Uhr"
      GRACE_PERIOD: ""
      W_DATE_1: ""
      W_DATE_2: ""
      W_DATE_3: ""
      EXAM_PERIOD: ""
      CANVAS_ID: ""
      CANVAS_LINK: ""
      ZOOM_LINK: ""
      ANNOUNCEMENTS_LINK: ""
      COURSE_LINK: ""
      FORUM_LINK: ""
      ANALYTICS_OPTOUT: ""
      FORMAT: "Seminar und Labor"
      ASSOCIATE_HEAD: "Dipl.-Ing. (FH) Tim Ziemann [tim.ziemann@hs-bremen.de](mailto:tim.ziemann@hs-bremen.de)"
      ANON_FEEDBACK: ""
